import { Button, Space } from "antd";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DnD Play",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Space>
          <Button type="link">
            <Link href="/roller">Roller</Link>
          </Button>
          <Button type="link">
            <Link href="/monster-list">Monsters</Link>
          </Button>
          <Button type="link">
            <Link href="/entities">Entities</Link>
          </Button>
          <Button type="link">
            <Link href="/arena">Arena</Link>
          </Button>
        </Space>
        {children}
      </body>
    </html>
  );
}
